spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: bookstorenoreplay@gmail.com
    password: aaaa bbbb cccc dddd
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/bookstore
    username: postgres
    password: password
  flyway:
    url: jdbc:postgresql://localhost:5432/bookstore
    user: postgres
    password: password
    driver-class-name: org.postgresql.Driver

jwt:
  password:
    encoder:
      secret: jwt-super-token-secret-key-also-very-long-and-secure
      iteration: 64
      keyLength: 256
  secret: jwt-super-dupper-token-secret-key-also-very-long-and-secure
  emailSecret: email-token-secret-key-also-very-long-and-secure
  emailExpiration: 86400000
  expiration: 3600
  issuer: bookstore